# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
