# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('bike_image_ref', models.CharField(max_length=250)),
                ('bike_model', models.CharField(max_length=250)),
                ('bike_colour', models.CharField(max_length=250)),
            ],
        ),
    ]
