# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0013_auto_20180126_1320'),
        ('profile', '0008_auto_20180126_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('tracking_device_number', models.CharField(max_length=250)),
                ('bike_image_ref', models.CharField(max_length=250)),
                ('bike_model', models.CharField(max_length=250)),
                ('bike_colour', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='serial_number',
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
