# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='bike_colour',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bike_image_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bike_model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tracking_device_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
