# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20180128_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Profile',
        ),
    ]
