# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 11:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
