# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeStation',
        ),
        migrations.AddField(
            model_name='route',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
