# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20171124_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikestation',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bikestation',
            name='lon',
            field=models.CharField(max_length=50),
        ),
    ]
