# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20171126_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikestation',
            name='lat',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='bikestation',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='bikestation',
            name='lon',
            field=models.CharField(max_length=250),
        ),
    ]
