# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20171126_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikestation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='bikestation',
            name='lon',
        ),
        migrations.AddField(
            model_name='bikestation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
