# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20171126_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeStation',
        ),
    ]
