# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 20:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0009_auto_20180114_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_id', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('route', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('distance', models.FloatField()),
                ('highest_elevation', models.FloatField()),
                ('lowest_elevation', models.FloatField()),
                ('top_speed', models.FloatField()),
                ('duration', models.TimeField()),
                ('saved_journey', models.BooleanField()),
                ('outside_geofence', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('work_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
