# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 14:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_journey_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='home_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='work_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
