# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 11:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20180126_1104'),
        ('track', '0011_auto_20180117_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.SerialNumber')),
            ],
        ),
        migrations.RemoveField(
            model_name='journey',
            name='journey_id',
        ),
        migrations.AlterField(
            model_name='journey',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.SerialNumber'),
        ),
        migrations.AlterField(
            model_name='location',
            name='serial_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.SerialNumber'),
        ),
    ]
