# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_auto_20180126_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofence',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='serial_number',
        ),
        migrations.DeleteModel(
            name='Geofence',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
