# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 13:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0009_auto_20180126_1320'),
        ('track', '0013_auto_20180126_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('distance', models.FloatField()),
                ('highest_elevation', models.FloatField()),
                ('lowest_elevation', models.FloatField()),
                ('top_speed', models.FloatField()),
                ('duration', models.TimeField()),
                ('saved_journey', models.BooleanField()),
                ('outside_geofence', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('work_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.UserInfo')),
            ],
        ),
    ]
