# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0018_auto_20180128_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geofence',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
