# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0022_auto_20180407_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 8, 19, 31, 12, 394323)),
            preserve_default=False,
        ),
    ]
